## 1. Данные по нормам питания

Достаем табл. 5.4 показателей по нормам питания из [документа МР 2.3.1.2432—08](https://rospotrebnadzor.ru/documents/details.php?ELEMENT_ID=4583) и создаем датафрейм на их основе.  

Копируем табл. из документа и делаем предобработку в Excel (удобно т.к. данные небольшие):
0. Оставлем только данные по детям 11-14 и 14- 18 лет
1. Дублирование значений для объединенных ячеек
2. Замена десяничного знака
3. Приведение всех единиц массы к мг
4. Привеление показателей в % к абсолютным цифрам
5. Где дан диапазон - "от-до" - для сведения к одной цифре взято среднее значение диапазона

Помнить: Показатели <b>"холестерин"</b> и <b>"% сахара по ккал"</b> - знак "<" таблице - т.е. "не более"- оставлена просто цифра!

In [2]:
import pandas as pd

day_norm = pd.read_excel('mr-2.3.1.2432_08_data.xlsx', index=False)
day_norm

day_norm.to_csv('day_norm.csv', index=False)

In [4]:
day_norm = pd.read_csv('day_norm.csv')
day_norm.head()

                                item  M 11-14  F 11-14  M 14-18  F 14-18
0                      Энергия, ккал   2500.0   2300.0   2900.0   2500.0
1                         Белок , мг  75000.0  69000.0  87000.0  75000.0
2  в т. ч. животного белка, доля, мг  45000.0  41400.0  52200.0  45000.0
3                   доля по ккал, мг   9000.0   8280.0  10440.0   9000.0
4                           Жиры, мг  83000.0  77000.0  97000.0  83000.0

In [12]:
mcd_menu = pd.read_csv('mcd_menu.csv')
mcd_menu.head ()

,Category,Item,Serving Size,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [16]:
sb_menu_drinks = pd.read_csv('sb_menu_drinks.csv')
sb_menu_drinks.head ()

,Item,Calories,Fat (g),Carb. (g),Fiber (g),Protein,Sodium
0,Cool Lime Starbucks Refreshers™ Beverage,45,0,11,0,0,10
1,Ombré Pink Drink,-,-,-,-,-,-
2,Pink Drink,-,-,-,-,-,-
3,Strawberry Acai Starbucks Refreshers™ Beverage,80,0,18,1,0,10
4,Very Berry Hibiscus Starbucks Refreshers™ Beve...,60,0,14,1,0,10

In [30]:
sb_menu_food = pd.read_csv('sb_menu_food.csv', encoding='cp1251')
sb_menu_food.head ()

   яюI  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5
0  NaN         NaN         NaN         NaN         NaN         NaN
1  NaN         NaN         NaN         NaN         NaN         NaN
2  NaN         NaN         NaN         NaN         NaN         NaN
3  NaN         NaN         NaN         NaN         NaN         NaN
4  NaN         NaN         NaN         NaN         NaN         NaN

In [28]:
# Лайфхак чтобы узнать кодировку файла
with open('sb_menu_food.csv') as f:
    print(f)

<_io.TextIOWrapper name='sb_menu_food.csv' mode='r' encoding='cp1251'>